title: <a href="https://anafdal.github.io/resume">Ana F Dalipi</a> 
logo: "/images/IMG_0277.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Graphics Technology Purdue Master Student
  <br><br>
   Immersive Analytics | Data Visualization | Data Analytics
  <br><br>
  <a href="https://www.linkedin.com/in/ana-fiona-dalipi-516503132/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
